server:
  port: 8088

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/books
    username: postgres
    password: postgres

  output:
    ansi:
      enabled: ALWAYS

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: localhost
    port: 1025
    username: allan
    password: allan
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enable: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

application:
  security:
    jwt:
      secret-key: d856e8cc6782427094b5294523b3ab03aabe8a5f032cacb0cec559fd17853d26b19e0f991769f9acd2aa9485d8de0abcc799000c25c731a1983418f6fe63bd30
      expiration: 8640000
  mailing:
    frontend:
      activation-url: http://localhost:4200/activate-account
  file:
    upload:
      photos-output-path: ./uploads